channels:
  - defaults
dependencies:
  - python=3.11
  - pytorch-cuda=11.8
  - torchaudio
  - pytorch
  - torchvision
  - tensorflow
  - cudatoolkit
  - cudnn
  - datasets
  - scikit-learn
  - seaborn
  - gxx_linux-64
  - gcc_linux-64
  - mpich
  - pip:
    - accelerate==0.28.0
    - advertorch==0.2.3
    - anndata==0.10.9
    - deepspeed==0.14.0
    - diffusers==0.30.3
    - efficientnet-pytorch==0.7.1
    - huggingface-hub==0.25.0
    - opacus==1.4.0
    - timm==0.9.16
    - transformers==4.39.1
    - wandb==0.16.6
    - umap-learn==0.5.6
